### ISSUE TITLE
lxml compile out of memory error

### ISSUE THREAD

**Issue by bcfuchs** [ExCiteS/geokey-epicollect#7]
module may die on lxml compile. Means you need to increase memory. 

e.g. 

`x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/libxml2 -I/var/www/geokey/env/build/lxml/src/lxml/includes -I/usr/include/python2.7 -c src/lxml/lxml.etree.c -o build/temp.linux-x86_64-2.7/src/lxml/lxml.etree.o -w`

`x86_64-linux-gnu-gcc: internal compiler error: Killed (program cc1`)

More memory!

**Comment by juliusosokinas** [comment]
Closed because of inactivity.
